/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/workspace/ams-document/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-0f0d0151",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f0d0151").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-5cc728ea",
    path: "/dev/component-lifecycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5cc728ea").then(next)
    },
  },
  {
    name: "v-d88ef170",
    path: "/dev/component-registry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d88ef170").then(next)
    },
  },
  {
    name: "v-1a44d408",
    path: "/dev/component-store-caches.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a44d408").then(next)
    },
  },
  {
    name: "v-f8aae02c",
    path: "/dev/function-registry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f8aae02c").then(next)
    },
  },
  {
    name: "v-690a8828",
    path: "/dev/registry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-690a8828").then(next)
    },
  },
  {
    name: "v-00cbe80a",
    path: "/intro/intro.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00cbe80a").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]