/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "AMS 使用文档",
  "description": "一个基于 JSON 动态解析微前端中后台前端/设计解决方案",
  "base": "/ams-document/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/images/logo.png",
        "actionText": "开始阅读 →",
        "actionLink": "/intro/intro.html",
        "footer": "MIT Licensed | Copyright © 2020-present XFE",
        "title": "FRONT PAGE"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0f0d0151",
      "path": "/",
      "lastUpdated": "4/15/2020, 4:44:58 AM"
    },
    {
      "title": "买量后台 - CostPerBuy",
      "frontmatter": {
        "title": "买量后台 - CostPerBuy"
      },
      "regularPath": "/customize-projects/cost-per-buy.html",
      "relativePath": "customize-projects/cost-per-buy.md",
      "key": "v-4fbb188a",
      "path": "/customize-projects/cost-per-buy.html",
      "headers": [
        {
          "level": 2,
          "title": "买量后台 - CostPerBuy",
          "slug": "买量后台-costperbuy"
        },
        {
          "level": 2,
          "title": "基本结构",
          "slug": "基本结构"
        },
        {
          "level": 2,
          "title": "组件列表",
          "slug": "组件列表"
        }
      ],
      "lastUpdated": "4/23/2020, 11:24:03 AM"
    },
    {
      "title": "布局",
      "frontmatter": {
        "title": "布局"
      },
      "regularPath": "/customize-projects/layout.html",
      "relativePath": "customize-projects/layout.md",
      "key": "v-6cdcd26c",
      "path": "/customize-projects/layout.html",
      "headers": [
        {
          "level": 2,
          "title": "布局 - Layout",
          "slug": "布局-layout"
        },
        {
          "level": 2,
          "title": "布局 - Layout.Custom",
          "slug": "布局-layout-custom"
        },
        {
          "level": 2,
          "title": "布局 - Layout.Basic",
          "slug": "布局-layout-basic"
        }
      ],
      "lastUpdated": "4/24/2020, 7:12:36 AM"
    },
    {
      "title": "组件仓库",
      "frontmatter": {
        "title": "组件仓库"
      },
      "regularPath": "/dev/component-registry.html",
      "relativePath": "dev/component-registry.md",
      "key": "v-d88ef170",
      "path": "/dev/component-registry.html",
      "headers": [
        {
          "level": 2,
          "title": "组件仓库",
          "slug": "组件仓库"
        },
        {
          "level": 3,
          "title": "组件仓库 - html",
          "slug": "组件仓库-html"
        },
        {
          "level": 3,
          "title": "组件仓库 - antd",
          "slug": "组件仓库-antd"
        },
        {
          "level": 3,
          "title": "组件仓库 - @ant-design/pro-layout",
          "slug": "组件仓库-ant-design-pro-layout"
        },
        {
          "level": 3,
          "title": "组件仓库 - ams",
          "slug": "组件仓库-ams"
        }
      ],
      "lastUpdated": "4/23/2020, 11:23:46 AM"
    },
    {
      "title": "组件存储缓存",
      "frontmatter": {
        "title": "组件存储缓存"
      },
      "regularPath": "/dev/component-store-caches.html",
      "relativePath": "dev/component-store-caches.md",
      "key": "v-1a44d408",
      "path": "/dev/component-store-caches.html",
      "headers": [
        {
          "level": 2,
          "title": "组件存储缓存",
          "slug": "组件存储缓存"
        },
        {
          "level": 2,
          "title": "组件存储缓存部分源码",
          "slug": "组件存储缓存部分源码"
        },
        {
          "level": 2,
          "title": "用法",
          "slug": "用法"
        }
      ],
      "lastUpdated": "4/15/2020, 4:44:58 AM"
    },
    {
      "title": "函数仓库",
      "frontmatter": {
        "title": "函数仓库"
      },
      "regularPath": "/dev/function-registry.html",
      "relativePath": "dev/function-registry.md",
      "key": "v-f8aae02c",
      "path": "/dev/function-registry.html",
      "headers": [
        {
          "level": 2,
          "title": "函数仓库",
          "slug": "函数仓库"
        },
        {
          "level": 2,
          "title": "函数转换为 json 原理",
          "slug": "函数转换为-json-原理"
        },
        {
          "level": 3,
          "title": "函数仓库 - antd",
          "slug": "函数仓库-antd"
        },
        {
          "level": 3,
          "title": "函数仓库 - ams",
          "slug": "函数仓库-ams"
        }
      ],
      "lastUpdated": "4/23/2020, 11:23:46 AM"
    },
    {
      "title": "组件生命周期",
      "frontmatter": {
        "title": "组件生命周期"
      },
      "regularPath": "/dev/component-lifecycle.html",
      "relativePath": "dev/component-lifecycle.md",
      "key": "v-5cc728ea",
      "path": "/dev/component-lifecycle.html",
      "headers": [
        {
          "level": 2,
          "title": "生命周期",
          "slug": "生命周期"
        },
        {
          "level": 3,
          "title": "组件挂载/组件卸载",
          "slug": "组件挂载-组件卸载"
        }
      ],
      "lastUpdated": "4/14/2020, 3:47:36 PM"
    },
    {
      "title": "内置接口 API",
      "frontmatter": {
        "title": "内置接口 API"
      },
      "regularPath": "/dev/internal-api.html",
      "relativePath": "dev/internal-api.md",
      "key": "v-154ee264",
      "path": "/dev/internal-api.html",
      "headers": [
        {
          "level": 2,
          "title": "内置接口 API",
          "slug": "内置接口-api"
        },
        {
          "level": 2,
          "title": "1. 选择项目 (路径: /)",
          "slug": "_1-选择项目-路径"
        },
        {
          "level": 2,
          "title": "2. 开发环境登录 (路径: /login)",
          "slug": "_2-开发环境登录-路径-login"
        }
      ],
      "lastUpdated": "4/23/2020, 11:24:03 AM"
    },
    {
      "title": "内置路由",
      "frontmatter": {
        "title": "内置路由"
      },
      "regularPath": "/dev/internal-routes.html",
      "relativePath": "dev/internal-routes.md",
      "key": "v-0f12c62c",
      "path": "/dev/internal-routes.html",
      "headers": [
        {
          "level": 2,
          "title": "内置路由",
          "slug": "内置路由"
        },
        {
          "level": 2,
          "title": "常规流程",
          "slug": "常规流程"
        }
      ],
      "lastUpdated": "4/23/2020, 11:24:03 AM"
    },
    {
      "title": "仓库",
      "frontmatter": {
        "title": "仓库"
      },
      "regularPath": "/dev/registry.html",
      "relativePath": "dev/registry.md",
      "key": "v-690a8828",
      "path": "/dev/registry.html",
      "headers": [
        {
          "level": 2,
          "title": "仓库",
          "slug": "仓库"
        }
      ],
      "lastUpdated": "4/23/2020, 11:23:46 AM"
    },
    {
      "title": "状态管理",
      "frontmatter": {
        "title": "状态管理"
      },
      "regularPath": "/fe-customize/state-management.html",
      "relativePath": "fe-customize/state-management.md",
      "key": "v-1b6a6fca",
      "path": "/fe-customize/state-management.html",
      "headers": [
        {
          "level": 2,
          "title": "状态管理",
          "slug": "状态管理"
        }
      ],
      "lastUpdated": "4/16/2020, 6:07:20 AM"
    },
    {
      "title": "AMS 介绍",
      "frontmatter": {
        "title": "AMS 介绍"
      },
      "regularPath": "/intro/intro.html",
      "relativePath": "intro/intro.md",
      "key": "v-00cbe80a",
      "path": "/intro/intro.html",
      "headers": [
        {
          "level": 2,
          "title": "AMS 是什么？",
          "slug": "ams-是什么？"
        },
        {
          "level": 2,
          "title": "面向用户",
          "slug": "面向用户"
        },
        {
          "level": 2,
          "title": "技术",
          "slug": "技术"
        }
      ],
      "lastUpdated": "4/14/2020, 11:18:15 AM"
    }
  ],
  "themeConfig": {
    "docsDir": "docs",
    "repo": "XFETeam/ams-document",
    "repoLabel": "文档来源",
    "editLinks": true,
    "editLinkText": "在 GitHub 上编辑这篇文档",
    "lastUpdated": "最后更新时间：",
    "sidebar": [
      {
        "title": "介绍",
        "collapsable": false,
        "sidebarDepth": 2,
        "children": [
          "/intro/intro"
        ]
      },
      {
        "title": "开发",
        "collapsable": false,
        "sidebarDepth": 2,
        "children": [
          "/dev/registry",
          "/dev/component-registry",
          "/dev/function-registry",
          "/dev/component-lifecycle",
          "/dev/component-store-caches",
          "/dev/internal-routes",
          "/dev/internal-api"
        ]
      },
      {
        "title": "定制项目",
        "collapsable": false,
        "sidebarDepth": 2,
        "children": [
          "/customize-projects/cost-per-buy",
          "/customize-projects/layout"
        ]
      }
    ],
    "serviceWorker": {
      "updatePopup": {
        "message": "发现新内容可用.",
        "buttonText": "刷新"
      }
    },
    "nav": []
  }
}